---
title: Homework 5 - Coding a navigation system
author: Joel John
date: 2/20/2024
format:
  html:
    embed-resources: true
    theme: cosmo
---

* [LINK to GITHUB](https://github.com/cmsc-vcu/cmsc475-sp2024-hw5-johnjm2.git)
* [LINK to FIGMA PROTOTYPE CODE](https://www.figma.com/file/AJ24JC8fjyHv92X2mmaDeK/HW4?type=design&node-id=34%3A124&mode=design&t=NIhS6K6OffW6vbVe-1)



# Introduction

The story of the young man unfolds through a journey of self-discovery, passion, and growth. From the strumming of his guitar on a stage filled with passion, navigating adventures on the open sea, to embracing diversity through community engagement, and innovating for a sustainable future in his lab. He explores his creativity in a vibrant art studio, stands resilient against life's challenges, and fosters deep connections with those around him. His journey, marked by curiosity and the empowerment of others, culminates in a moment of serene reflection, symbolizing the harmonious balance he's achieved. Through diverse experiences, he learns the value of each facet of his life, weaving them into a rich tapestry that defines his unique path.

The purpose of the naviagation strategy is for the card viewers to understand a beautify jouney of a young man but going through each picture by clicking arrows.


# Navigation Goals

The navigation goal is for the viewers to understand the story of a young man's journey going through each pictures by clicking arrows.

- Passion for music and the arts, as seen through his immersive guitar performances.
- Adventure-seeking spirit, demonstrated by his ventures on the open sea.
- Innovative mindset, with a focus on sustainable technologies.
- Resilience in the face of challenges, standing strong against adversity.
- Creativity in expression, captured in the vibrant chaos of his art studio.
- Diversity: Celebrates inclusivity and unity through community engagement.
- Journey's End: Symbolizes a harmonious conclusion of diverse life experiences.

# Navigation Elements

- The users would navigate by clicking arrow icons (Left and Right)


# Figma mockup

- Simply click the arrow icons to navigate through each panels.


```{=html}
<center>
<iframe
src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fproto%2FAJ24JC8fjyHv92X2mmaDeK%2FHW4%3Ftype%3Ddesign%26node-id%3D34-124%26t%3D38fKEtMMyox1b1FC-1%26scaling%3Dscale-down%26page-id%3D1%253A2%26starting-point-node-id%3D1%253A3%26mode%3Ddesign"
style="border: 1px solid rgba(0, 0, 0, 0.1);"
width="800" height="450"  
data-external="1"
allowfullscreen
></iframe>
</center>
```


# User Testing

I shared it with my close friend. I asked him how it looks like and is it user-friendly. He said it is user-friendly and he was able to understand most of themes of the young man's journey. Though, I could improve on making it look better and be more creative.


# Implementation


```{=html}
<center>
<iframe
src="https://editor.p5js.org/johnjm2/full/h1Kud9-mv"
style="border: 1px solid rgba(0, 0, 0, 0.1);"
width="800"
height="450"  
data-external="1"
allowfullscreen="allowfullscreen"
webkitallowfullscreen="webkitallowfullscreen"
mozallowfullscreen="mozallowfullscreen"
allow="geolocation *; microphone *; camera *; midi *; encrypted-media *; autoplay *; clipboard-write *; display-capture *"
></iframe>
</center>
```

# Reflection


Working on this project was really enjoyable. It took me about five hours, and I learned a lot, especially about how different parts of the code work together. If I had more time at the start, I would've spent it understanding the code better, which would've made things easier. The best part was seeing the panels change when I navigated through them – it felt great to see my work in action. The hardest part was getting all the different classes to work together smoothly. If I had more time, I'd love to try adding more features and experimenting with new ideas.

